In [59]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

Project Objective is Forecasting PE (Output, dependent variable). AT, V, AP, RH (Input, independent vairable)
- data set with time should be done sequentially for test split
- dataset without time should be done randomly for test split

In [28]:
df = pd.read_excel(r"C:\Users\codchen1\Desktop\data.xlsx")

In [30]:
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [33]:
df.shape

(9568, 5)

1. Getting the input(independent varaible/ X) and output (dependent varaibles/ Y / What you want to forecast)

In [44]:
# Getting X Variables, I need the all the rows and first 4 columns/index.
# The first part is rows, the second part is columns.
# .values at the end turns it into array, needed for machine learning
x = df.iloc[:, :-1].values # All rows, all the columns except the last column
# You can also do:
# x = df.iloc[:, 0:3].values
# If excluding last two columns, do -2

In [49]:
# y= PE, -1 means exactly last column, if -2, it means exactly second to last column
y = df.iloc[:, -1].values

2. Creating train/test set
- random_state = 0, data will be split the same way every time the code is run

In [50]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [52]:
model = LinearRegression()

3. Training the model

In [53]:
model.fit(x_train, y_train)

LinearRegression()

4. Inference  
- The results from y_predict and y_test are relatively close

In [55]:
y_predict = model.predict(x_test)
y_predict

array([431.42761597, 458.56124622, 462.75264705, ..., 469.51835895,
       442.41759454, 461.88279939])

In [56]:
y_test

array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28])

Making prediction of single data point  
AT = 51, V = 40, AP = 1000, RH = 75

In [57]:
model.predict([[15,40,1000,75]])

array([465.80771895])

5. Evaluating the model using R-Squared and Adjusted R-Sqaured

In [62]:
# R-Squared: goodness of fit
r2 = r2_score(y_test, y_predict)
r2

0.9325315554761303

In [65]:
# Adjusted R-Squared, 0.7 is okay, <0.4 is terrible.
k = x_test.shape[1]
n = x_test.shape[0]
adj_r2 = 1-(1-r2)*(n-1)/(n-k-1)

In [66]:
# It make sures we only add variables that will bring substantial improvement to the model.
adj_r2

0.9323901862890713